language: php

php:
  - 7.2
  - 7.3

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction --quiet
  - php artisan key:generate

before_install:
  - mysql -e 'CREATE DATABASE laravel;'

script:
  - phpunit


after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT

services:
  - mysql

notifications:
  email: false

env:
  global:
    - CC_TEST_REPORTER_ID=55a480e1a17a11dfa1c76cd2b48b6b010037952c2c9b488f9f349eca640b892d
