language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate

before_install:
  - mysql -e 'CREATE DATABASE laravel;'

script:
  - phpunit

services:
  - mysql

notifications:
  email: false
